name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libpython3.8-dev
      - name: Build
        run: |
          g++ $(find src/ -name "*.cpp") -o menial.bin -std=c++11 -pthread -Wall -I /usr/include/python3.8/ -l python3.8 -I src/include/ -lssl -lcrypto -D TEST=0

      - name: Run a multi-line script
        run: |
          mkdir -p menial_0.1.$GITHUB_RUN_NUMBER
          mkdir -p menial_0.1.$GITHUB_RUN_NUMBER/DEBIAN
          mkdir -p menial_0.1.$GITHUB_RUN_NUMBER/usr
          mkdir -p menial_0.1.$GITHUB_RUN_NUMBER/usr/share
          mkdir -p menial_0.1.$GITHUB_RUN_NUMBER/usr/share/menial
          mkdir -p menial_0.1.$GITHUB_RUN_NUMBER/usr/bin
          mkdir -p menial_0.1.$GITHUB_RUN_NUMBER/etc/menial
          mkdir -p menial_0.1.$GITHUB_RUN_NUMBER/usr/share/menial/resources/static/
          mkdir -p menial_0.1.$GITHUB_RUN_NUMBER/usr/share/menial/http/
          cp menial.bin menial_0.1.$GITHUB_RUN_NUMBER/usr/bin/menial.bin
          cp deployment/menial menial_0.1.$GITHUB_RUN_NUMBER/usr/bin/menial
          cp deployment/menial.json menial_0.1.$GITHUB_RUN_NUMBER/etc/menial/
          cp -r deployment/resources/ menial_0.1.$GITHUB_RUN_NUMBER/usr/share/menial/
          cp -r deployment/default menial_0.1.$GITHUB_RUN_NUMBER/usr/share/menial/http/
          echo "Package: menial" > menial_0.1.$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Version: 0.1.$GITHUB_RUN_NUMBER" >> menial_0.1.$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Section: base" >> menial_0.1.$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Priority: optional" >> menial_0.1.$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Architecture: amd64" >> menial_0.1.$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Depends: python3 (>=3.6), python3-dev (>=3.6)" >> menial_0.1.$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Description: Always at your service!" >> menial_0.1.$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Maintainer: Christian Kokoska (info@softcreate.de)" >> menial_0.1.$GITHUB_RUN_NUMBER/DEBIAN/control
          cat menial_0.1.$GITHUB_RUN_NUMBER/DEBIAN/control
          dpkg-deb --build menial_0.1.$GITHUB_RUN_NUMBER

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: menial_0.1.${{ github.run_number }}.deb
          path: menial_0.1.${{ github.run_number }}.deb
