# This is a basic workflow to help you get started with Actions

name: debian package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-dev
      - name: Build
        run: |
          g++ $(find src/ -name "*.cpp") -o menial.bin -std=c++11 -pthread -Wall -I /usr/include/python3.6m/ -l python3.6m -I src/include/ -lssl -lcrypto -D TEST=0

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir -p menial_$GITHUB_RUN_NUMBER
          mkdir -p menial_$GITHUB_RUN_NUMBER/DEBIAN
          mkdir -p menial_$GITHUB_RUN_NUMBER/usr
          mkdir -p menial_$GITHUB_RUN_NUMBER/usr/share
          mkdir -p menial_$GITHUB_RUN_NUMBER/usr/share/menial
          mkdir -p menial_$GITHUB_RUN_NUMBER/usr/bin
          mkdir -p menial_$GITHUB_RUN_NUMBER/etc/menial
          mkdir -p menial_$GITHUB_RUN_NUMBER/usr/share/menial/resources/static/
          mkdir -p menial_$GITHUB_RUN_NUMBER/usr/share/menial/http/
          cp menial.bin menial_$GITHUB_RUN_NUMBER/usr/bin/menial.bin
          cp deployment/menial menial_$GITHUB_RUN_NUMBER/usr/bin/menial
          cp deployment/menial.json menial_$GITHUB_RUN_NUMBER/etc/menial/
          cp -r deployment/resources/ menial_$GITHUB_RUN_NUMBER/usr/share/menial/
          cp -r deployment/default menial_$GITHUB_RUN_NUMBER/usr/share/menial/http/
          echo "Package: menial" > menial_$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Version: $GITHUB_RUN_NUMBER" >> menial_$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Section: base" >> menial_$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Priority: optional" >> menial_$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Architecture: amd64" >> menial_$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Depends: python3 (>=3.6), python3-dev (>=3.6)" >> menial_$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Description: Always at your service!" >> menial_$GITHUB_RUN_NUMBER/DEBIAN/control
          echo "Maintainer: Christian Kokoska (info@softcreate.de)" >> menial_$GITHUB_RUN_NUMBER/DEBIAN/control
          cat menial_$GITHUB_RUN_NUMBER/DEBIAN/control
          dpkg-deb --build menial_$GITHUB_RUN_NUMBER

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: menial_${{ env.GITHUB_RUN_NUMBER }}.deb
          path: menial_${{ env.GITHUB_RUN_NUMBER }}.deb
