name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-dev libpython3.8-dev npm
    - name: Build
      run: |
        g++ $(find src/ -name "*.cpp") -o menial_test.bin -std=c++11 -pthread -Wall -I /usr/include/python3.6m/ -l python3.6m -I src/include/ -lssl -lcrypto -lz -D TEST=1
    - name: Test
      run: |
        ./menial_test.bin
